export const INPUT_CHANGE = 'INPUT_CHANGE';
export const GET_WEATHER = 'GET_WEATHER';
export const SET_WEATHER = 'SET_WEATHER';
export const SET_COORD = 'SET_COORD';
export const SET_YOUR_LOCATION = 'SET_YOUR_LOCATION';
export const SET_OTHER_LOCATION = 'SET_OTHER_LOCATION';
